### ISSUE TITLE
Missing agda library file

### ISSUE THREAD

**Issue by jonaprieto** [effectfully/OTT#1]
Would you please add the agda library file (.agda-lib)?
I was considering indexing your library for agda-pkg. 
If so, let me know also if you're planning a release.

**Comment by effectfully** [comment]
This library is not supported. I also don't quite like it and I don't think it's very useful.

May I ask you to add the [Generic](https://github.com/effectfully/Generic) library? It's supported and is kind of useful.

**Comment by jonaprieto** [comment]
> This library is not supported. I also don't quite like it and I don't think it's very useful.
> 
Ok. It's fine.

> May I ask you to add the [Generic](https://github.com/effectfully/Generic) library? It's supported and is kind of useful.

It's indexed now Generic, I'll keep an eye for releases.
